# @package _global_

defaults:
  - _self_


# Model settings
model_path: hanshanxue/WorldStereo
model_type: worldstereo-memory-dmd  # worldstereo-camera, worldstereo-memory, worldstereo-memory-dmd

# Paths
input_path: examples/images
output_path: outputs

# Task type
task_type: camera_control  # camera_control, panorama, reconstruction
align_nframe: 8  # For multi-trajectory tasks

# Distributed/optimization
local_files_only: false
fsdp: false
w8a8: false
w8a8_all: false
w8a8_save_path: null

# Misc
seed: 1024

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
